Remove cpplint from DEPS
And update tools/lint to use cpplint.py from path.

DEPS was fetchling cpplint from `{chromium_git}/third_party/cpplint/google/styleguide`.

This repo no longer contains cpplint, and now instead is maintained in depot_tools.

The version in depot_tools contains a fix for python3.

Fixed: tint:794
Change-Id: I06c3f8a628ffa3e70887464b1da063b465c05c65
Reviewed-on: https://dawn-review.googlesource.com/c/tint/+/50743
Kokoro: Kokoro <noreply+kokoro@google.com>
Commit-Queue: David Neto <dneto@google.com>
Auto-Submit: Ben Clayton <bclayton@google.com>
Reviewed-by: David Neto <dneto@google.com>

diff --git a/tools/lint b/tools/lint
--- a/tools/lint
+++ b/tools/lint
@@ -18,20 +18,23 @@ ROOT_DIR="$( cd "${SCRIPT_DIR}/.." >/dev/null 2>&1 && pwd )"
 
 set -e  # fail on error
 
-FILTER="-runtime/references"
+if ! command -v cpplint.py &> /dev/null; then
+    echo "cpplint.py not found on PATH"
+    exit 1
+fi
 
+FILTER="-runtime/references"
 FILES="`find src -type f` `find samples -type f`"
 
-if command -v go &> /dev/null
-then
+if command -v go &> /dev/null; then
     # Go is installed. Run cpplint in parallel for speed wins
-    go run $SCRIPT_DIR/src/run-parallel/main.go   \
-         --only-print-failures                    \
-         ./third_party/cpplint/cpplint/cpplint.py \
-         --root=$ROOT_DIR                         \
-         --filter="$FILTER"                       \
+    go run $SCRIPT_DIR/src/run-parallel/main.go \
+         --only-print-failures                  \
+         cpplint.py                             \
+         --root=$ROOT_DIR                       \
+         --filter="$FILTER"                     \
          $ -- $FILES
 else
-    ./third_party/cpplint/cpplint/cpplint.py --root=$ROOT_DIR --filter="$FILTER" $FILES
+    cpplint.py --root=$ROOT_DIR --filter="$FILTER" $FILES
 fi
 
